schema_version: 1

context:
  version: "0.11.0"
  python_min: "3.10"

package:
  name: graphemeu

source:
  url: https://pypi.org/packages/source/g/graphemeu/graphemeu-${{ version }}.tar.gz
  sha256: d03e0f625dcf8c6ff81e52d85bacad3f1ecf66c54df27a2dbd0544a0d02903d4

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling
    - pip
  run:
    - python >=${{ python_min }}

tests:
  - python:
      imports:
        - grapheme
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"

about:
  summary: Unicode grapheme helpers
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/timendum/grapheme
  documentation: https://graphemeu.readthedocs.io/

extra:
  recipe-maintainers:
    - Brainor
